### ISSUE TITLE
Dependent properties

### ISSUE THREAD

**Issue by inktomi** [gradlex-org/build-parameters#136]
It would be nice if we could configure one property based on the value of another. For instance, in an android project, we might want to alter the way a build works if it's ran from within android studio. Android studio sets `android.injected.invoked.from.ide=true` but we might want to map that to a more generic flag that's used from the command line called `fastBuild` (for example). 

So, in the setup for `fastBuild` we might have something like this where we use something that results in a `Boolean`:

```kotlin
    bool("fastBuild") {
        description.set("Skips production logic resulting in much faster builds.")
        defaultValue.from("android.injected.invoked.from.ide" || anotherProperty)
    }
```

This would let us pull the default value from another variable, rather than hard coding it. I do see that we could pass in a `Provider<Boolean>` as the default value - could that be used to achieve this logic? 

Another option could be something like this, but it feels really messy (pseudocode..). This also might just be checking to see if we _have_ a property with the path, rather than what it's value is - it doesn't seem like you can do a "lazy" lookup and get a value. 

```kotlin
defaultValue.set(!buildParameters.parameters.get().none { it -> it.propertyPath == "android.injected.invoked.from.ide" })
```

**Comment by jjohannes** [comment]
This is a topic @britter already discussed many times. My concern is that we add too much complexity and functionality into this plugin. It feels like we might end up with a whole expression language to combine values.

For me, there is a line between the "build user" (person calling the build e.g. from the command line) and the "build author" (person using the type-safe accessors to setup the build logic). While the build authoring aspect is certainly important (hence the type-safe accessors) the main focus, from my perspective, should be on the build user so that she gets a clean understanding of what parameters exist and also gets error/warning if using something wrong. "Derived parameters" are something that only concern the "author" side, but not the "user" side.

What we always ended up with in our discussions is that if you have such a "derived value", you could define your own extensions/variables for this inside your build logic.

In your example. What about you define your own extension like this:

```
// Values used by the build author in the build configuration; not sen from "outside"
interface DerivedParameters {
    val fastBuild: Property<Boolean>
}
```

```
val derivedParameters = extensions.create<DerivedParameters>("derivedParameters")

derivedParameters.fastBuild.set(buildParameters.ci || buildParameters.dbHost == "127.0.0.1")
```

To use the generated build parameter accessors inside convention plugin code, you can have one subproject for the build parameters and another one for your custom code.

Here is a full example: https://github.com/gradlex-org/build-parameters/blob/derived_parameters_example/samples/basics/gradle/plugins/java-plugins/src/main/kotlin/my-java-library.gradle.kts

**Comment by inktomi** [comment]
That sample does work. Thank you. It's perhaps a little confusing to have two places for build variables, but with some documentation and team training I think it's maintainable.

**Comment by britter** [comment]
We understand how this would be a helpful feature. However, the challenge is that the build script DSL for defining parameters is made up of _meta_ types describing the actual types of the generated plugin. E.g. a build author describes a parameter of type `Boolean`, but they configure an object of type `BooleanParameter`. For this reason, you can't write something like `defaultValue.set(thisParam || thatParam)`. `thisParam` and `thatParam` are not of type `boolean`, so the `||` is not applicable. It would be possible to implement a set of combinator operations for all supported parameter types, but as pointed out by @jjohannes we're afraid that we will introduce a custom expression language that we would have to maintain.

For that reason, we've decided to close this for now. If we see more people asking for this, we may reconsider our decision.
